### ISSUE TITLE
Re-introduce pwm fully-on, fully-off, and fraction?

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/hello-embedded#2]
I removed `set-duty-cycle-fully-on`, `set-duty-cycle-fully-off`, and `set-duty-cycle-fraction`, because they seemed redundant with just calling `set-duty-cycle`. However, it may be the case that some chips distinguish between 0 and fully-off, and max and fully-on, or may have fractional levels that can't otherwise be represented, so we should consider re-introducing them.

**Comment by cpetig** [comment]
I looked inside embedded-hal and embassy and couldn't find any proof that set_duty_cycle alone wouldn't be enough, but I recall that at the point of designing it there was a limitation on some hardware. So I guess we should be flexible to re-introduce it later should the need arise.

**Comment by sunfishcode** [comment]
Sounds good. I've now filed https://github.com/sunfishcode/hello-embedded/pull/3 to document our expectations here.

**Comment by cpetig** [comment]
See https://matrix.to/#/!BHcierreUuwCMxVqOf:matrix.org/$_L916rubYL22T6FHzcQ8_hMFSH-h3PoA7a5HCdrL-EQ?via=matrix.org&via=catircservices.org&via=tchncs.de for an in depth explanation by a main author of embedded-hal on why fully-on and -off isn't needed anymore and is now just a frontend to set-duty-cycle.

**Comment by sunfishcode** [comment]
That's great, thanks!
